version: 2

references:
    steps: &steps
        working_directory: ~/repo
        steps:
            - checkout
            - run: apt-get -yqq update
            - run: apt-get -yqq install git unzip zip libpq-dev mysql-client libpng-dev
            - run: docker-php-ext-install pdo_pgsql pdo_mysql gd
            - run: curl -sS https://getcomposer.org/installer | php
            - run: chmod +x composer.phar
            - run: mv composer.phar /usr/local/bin/composer
            - run: composer config -g github-oauth.github.com $GITHUB_TOKEN
            - run: composer install -n --prefer-dist --no-progress -o
            - run: ./vendor/bin/phpunit

    environment: &environment
        - DB_DATABASE: testing
        - DB_USERNAME: testing
        - DB_PASSWORD: testing
        - APP_KEY: deela5kinohw0haekoothahSh8eexach

jobs:
    "php-7.1":
        docker:
            - image: php:7.1
              environment: *environment
        <<: *steps
    "php-7.2":
        docker:
            - image: php:7.2
              environment: *environment
        <<: *steps


workflows:
    version: 2
    test:
        jobs:
            - "php-7.1"
            - "php-7.2"
